# ----
# Site

title: Exercises - ISMATECH
description: Exercises List in Programmation.
url: https://exo.isma-tech.fr
google_analytics_key:
permalink: pretty
baseurl: https://exo.isma-tech.fr

# -----
# Build

timezone: Europe/Paris

collections:
  exercises:
    title: Exercices
    position_number: 1
  projects:
    title: Projets
    position_number: 2
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - readme.md
  - LICENSE

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      type: "exercises"
    values:
      _hide_content: true
  - scope:
      type: "projects"
    values:
      _hide_content: true

# -----------

types:
  - get
  - put
  - delete
  - post

languages:
  bash: Bash
  c: C
  css: CSS
  html: HTML
  java: Java
  javascript: JavaScript
  json: JSON
  php: PHP
  python: Python
  ruby: Ruby
  markdown: Markdown

_options:
  content_markdown:
    format: p h4 h5 h6
    bold: true
    italic: true
    link: true
    bulletedlist: true
    numberedlist: true
    image: true
    table: true
    styles: /css/editor.css
